accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.home, name='home'),
    path('boards/<int:pk>/', views.board_topics, name='board_topics'),
    path('boards/<int:pk>/new_topic', views.new_topic, name='new_topic'),
    path('boards/<int:pk>/topics/<topic_pk>/', views.topic_posts, name='topic_posts'),
    path('boards/<int:pk>/topics/<topic_pk>/reply/', views.reply_topic, name='reply_topic'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('boards.urls', namespace='boards')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

]

accounts/models.py
from django.db import models

# Create your models here.

boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)
    hot = models.BooleanField(blank=True, null=True, default=False)

    def __str__(self):
        return f"{self.subject}"

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.SET_NULL)
    
    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(10)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

boards/forms.py
from django import forms
from .models import Topic, Post

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(
        attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
    ), max_length=4000, help_text='The max length of the text is 4000.')

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    """Form definition for Post."""

    class Meta:
        """Meta definition for Postform."""

        model = Post
        fields = ('message',)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect

from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, "accounts/signup.html", {'form':form})

boards/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Board, Topic, Post
from .forms import NewTopicForm, PostForm


def home(request):
    boards = Board.objects.all()
    topics = Topic.objects.filter(hot=True)
    return render(request, "boards/home.html", {'boards':boards,'topics':topics})

def board_topics(request, pk):
    board = get_object_or_404(Board, pk=pk)
    return render(request, "boards/topic.html", {'board':board})

@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            Post.objects.create(
                message = form.cleaned_data.get('message'),
                topic = topic,
                created_by= request.user
            )
            return redirect('boards:topic_posts', pk=pk, topic_pk=topic.pk)  # TODO: redirect to the created topic page
    else:
        form = NewTopicForm()
    return render(request, "boards/new_topic.html", {'board':board, 'form':form})


def topic_posts(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    return render(request, "boards/topic_posts.html", {'topic':topic})

@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            return redirect('boards:topic_posts', pk=pk, topic_pk=topic_pk)
    else:
        form = PostForm()
    return render(request, "boards/reply_topic.html", {'topic':topic, 'form':form})

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Sign up
{% endblock title %}
{% block content %}
<h1>Sign up</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Sign up">
</form>
{% endblock content %}

boards/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <!-- MDB icon -->
    <link rel="icon" href="{% static 'img/mdb-favicon.ico' %}" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />

    <link href="https://fonts.googleapis.com/css?family=Parisienne:regular" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lora:regular,500,600,700,italic,500italic,600italic,700italic"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Hind+Madurai:300,regular,500,600,700" rel="stylesheet" />

    <style>
        h1 {
            font-family: Parisienne;
        }

        h6 {
            font-family: Lora;
        }
    </style>
</head>

<body>

    <div class="container mt-5">
        <div class="row">
            <div class="col-8">
                <h1><a href="/">Boards</a></h1>
            </div>
            <div class="col-4">
                
                {% if user.is_authenticated %}
                Hello,
                <!-- Dark -->
                <div class="btn-group">
                    <a type="button" class="btn btn-dark dropdown-toggle" data-mdb-toggle="dropdown"
                        aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                    </ul>
                </div>
               
                {% else %}
                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
                <a class="btn btn-primary" href="{% url 'accounts:signup' %}">Sign up</a>
                {% endif %}
                    

               
                
                
            </div>


        </div>
        {% block content %}

        {% endblock content %}

    </div>



    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
</body>

</html>

boards/templates/boards/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}
{% block content %}

<div class="row">
    {% for board in boards %}
    <h6>
        <a href="{% url 'board:board_topics' board.pk %}">{{ board.name }}</a> <br>
        <hr>
    </h6>
    {% endfor %}
</div>
<div class="row">
<h1>Hot topics!</h1>
</div>
{% for hot in topics %}

<div class="row justify-content-center">
        <p>
            <a href="">{{ hot }}</a>
        </p>
    
</div>
{% endfor %}

{% endblock content %}

boards/templates/boards/new_topic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Start a New Topic
{% endblock %}

{% block content %}
<style>
    span.asteriskField {
        display: none;
    }
</style>
<div class="row">
    <div class="col-10">
        <h6>{{ board.name }}</h6>
    </div>
</div>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mt-3">Post</button>
</form>
{% endblock %}

boards/templates/boards/reply_topic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %}
Post a reply
{% endblock %}


{% block content %}

<form method="post" class="mb-4">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mt-3">Post a reply</button>
</form>

{% for post in topic.posts.all %}
<div class="card mb-2">
    <div class="card-body p-3">
        <div class="row mb-3">
            <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
            </div>
            <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
            </div>
        </div>
        {{ post.message }}
    </div>
</div>
{% endfor %}

{% endblock %}

boards/templates/boards/topic.html
{% extends 'base.html' %}

{% block title %}
{{ board.name }}
{% endblock title %}
{% block content %}
<div class="row">
    <div class="col-10">
        <h6>{{ board.name }}</h6>
    </div>
    <div class="col-2">
        <a href="{% url 'boards:new_topic' board.pk %}">New topic</a>
    </div>
    
</div>
{% for topic in board.topics.all %}

<div class="row">
    <div class="col">
        >><a href="{% url 'boards:topic_posts' board.pk topic.pk %}">{{ topic.subject }}</a>
        <small class="fst-italic "> started by
            {{ topic.starter.username }}

            {{ topic.last_updated }}
        </small><<
    </div>


</div>
{% endfor %}

{% endblock content %}

boards/templates/boards/topic_posts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Topic posts
{% endblock title %}
{% block content %}
<!-- <div class="row"> -->
    <!-- <h2>{{ topic.subject }} - {{ topic.board.name }}</h2>  -->
<!-- </div> -->
<div class="mb-4">
    <a href="{% url 'boards:reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
  </div>

  {% for post in topic.posts.all %}
    <div class="card mb-2 
    {% if forloop.first %}
    border border-dark
    {% endif %}
      ">
      {% if forloop.first %}
      <div class="card-header text-white text-center bg-dark py-2 px-3">{{ topic.subject }} </div>
    {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'img/avatar.svg' %}" alt="{{ post.created_by.username }}" class="w-50">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
            </div>
            {{ post.message }}
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="#" class="btn btn-primary btn-sm" role="button">Edit</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock content %} 